"""Citation Parser & Evidence Validator — Phase 4 Part 11 & Part 12.

Parses, validates, and enforces evidence citations:
    - Extracts inline citation tags ([EVID-ML-001], [SHAP-001], [GRAPH-001], [RAG-001]).
    - Validates that every citation in the response exists in the Evidence Bundle.
    - Strips or flags unsupported/fabricated citations.
"""
from __future__ import annotations

import re
from typing import List, Dict, Any, Set, Tuple
from src.utils.logger import get_logger

logger = get_logger("genai_citations")

CITATION_REGEX = re.compile(r"\[(EVID-[A-Z0-9-]+|RAG-[0-9]+|SHAP-[0-9]+|GRAPH-[0-9]+|ML-[0-9]+)\]")


def extract_citations(text: str) -> List[str]:
    """Extract unique inline citation tags from text.

    Example: "High probability [EVID-ML-001]." -> ["EVID-ML-001"]
    """
    matches = CITATION_REGEX.findall(text)
    # Deduplicate while preserving order
    seen: Set[str] = set()
    result = []
    for m in matches:
        if m not in seen:
            seen.add(m)
            result.append(m)
    return result


def validate_citations(
    response_text: str, valid_citation_ids: Set[str]
) -> Tuple[bool, List[str], List[str]]:
    """Validate that every citation in response_text exists in valid_citation_ids.

    Args:
        response_text: Text output generated by LLM.
        valid_citation_ids: Set of valid Evidence Item citation IDs.

    Returns:
        (is_valid, extracted_citations, invalid_citations) tuple.
    """
    found_citations = extract_citations(response_text)
    invalid_citations = [c for c in found_citations if c not in valid_citation_ids]

    is_valid = len(invalid_citations) == 0

    if not is_valid:
        logger.warning(
            "Citation validation failed! Found %d invalid/fabricated citations: %s",
            len(invalid_citations), invalid_citations
        )
    else:
        logger.info("Citation validation passed cleanly (%d verified citations).", len(found_citations))

    return is_valid, found_citations, invalid_citations
