"""Pydantic Schemas for Evidence Bundles, Agents & API Endpoints — Phase 4.

Defines strict structured data contracts for Evidence Items, Evidence Bundles,
Investigation Responses, Reports, Data Analyst SQL Queries, and RAG search responses.
"""
from __future__ import annotations

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class EvidenceItem(BaseModel):
    """Single item of verified evidence from ML, SHAP, Graph, or RAG."""

    citation_id: str = Field(..., description="Unique citation identifier (e.g. EVID-ML-001, RAG-001)")
    source: str = Field(..., description="Source module (e.g. model_prediction, shap, graph, policy_document)")
    field: str = Field(..., description="Target feature or policy section name")
    value: Any = Field(..., description="Measured numerical, categorical, or textual value")
    description: str = Field(..., description="Human-readable evidence summary")
    timestamp: Optional[str] = Field(None, description="Timestamp of evidence generation")


class EvidenceBundle(BaseModel):
    """Deterministic collection of all case evidence before LLM processing."""

    evidence_bundle_id: str = Field(..., description="Bundle unique identifier")
    transaction_id: int = Field(..., description="Target Transaction ID")
    transaction_data: Dict[str, Any] = Field(default_factory=dict)
    ml_evidence: Dict[str, Any] = Field(default_factory=dict)
    shap_evidence: List[Dict[str, Any]] = Field(default_factory=list)
    graph_evidence: Dict[str, Any] = Field(default_factory=dict)
    anomaly_evidence: Dict[str, Any] = Field(default_factory=dict)
    retrieved_policy_evidence: List[Dict[str, Any]] = Field(default_factory=list)
    all_evidence_items: List[EvidenceItem] = Field(default_factory=list)


class InvestigationResponse(BaseModel):
    """Structured response from the Fraud Investigator Agent."""

    transaction_id: int
    case_overview: str
    risk_tier: str
    calibrated_score: float
    risk_indicators: List[str]
    ml_evidence_summary: str
    behavioral_anomaly_summary: str
    graph_relationship_summary: str
    policy_guidance: str
    recommended_questions: List[str]
    evidence_backed_conclusion: str
    citations: List[str]


class InvestigationReport(BaseModel):
    """Formal investigation report generated by Reporting Agent."""

    report_id: str
    transaction_id: int
    generated_at: str
    title: str
    markdown_content: str
    referenced_citations: List[str]


class DataAnalystQuery(BaseModel):
    """Analyst natural language query for SQL Analytics Agent."""

    question: str = Field(..., description="Natural language analytics question")


class DataAnalystResponse(BaseModel):
    """Response from Data Analyst Agent."""

    question: str
    generated_sql: str
    is_safe: bool
    explanation: str
    query_results: List[Dict[str, Any]] = Field(default_factory=list)


class RAGSearchQuery(BaseModel):
    """Search query for RAG hybrid retriever."""

    query: str
    top_k: int = 5


class RAGSearchResponse(BaseModel):
    """Search response from RAG hybrid retriever."""

    query: str
    retrieved_chunks: List[Dict[str, Any]]
